[package]
name = "ctf-hunter-ebpf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
aya-ebpf.workspace = true
ctf-hunter-common = { path = "../ctf-hunter-common" }

[lib]
path = "src/lib.rs"

[build-dependencies]
which = "8.0"

[[bin]]
name = "ctf-hunter-ebpf"
path = "src/main.rs"
test = false
bench = false

[lints.rust]
unsafe_code = "allow"
